version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_ACCESS_TOKEN_SECRET=acces_secret
      - JWT_REFRESH_TOKEN_SECRET=jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
